[tool.poetry]
name = "num-lin-algebra"
version = "0.1.0"
description = ""
authors = ["lentilus <lentilus@mailbox.org>"]

[tool.poetry.dependencies]
python = "3.10.15"
numpy = "^2.1.3"
pytest = "^8.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
